# Test that the github action it working. Based on example here: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#example-using-a-private-action
name: Test Action

# Run every time a tag is pushed to main. Won't trigger on tag names including including a /
on:
  - push
  - workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run check links action
        uses: ./
        id: check-links
        with:
          url: 'https://threefold.io'
          warnings: 'all'